process.env.DB_FILE='/tmp/chicken-shop-v1-test.db'; require('fs').rmSync(process.env.DB_FILE,{force:true});
const test=require('node:test'), assert=require('node:assert/strict'); const {start}=require('../src/server'); const db=require('../src/db/database');
let server,base,customer,owner,address,product,order;
const request=async(path,opts={})=>{let r=await fetch(base+path,{...opts,headers:{'content-type':'application/json',...(opts.token?{authorization:'Bearer '+opts.token}:{})},body:opts.body?JSON.stringify(opts.body):undefined});return {status:r.status,data:await r.json()}};
test('01 server starts',async()=>{server=await start(0);base=`http://127.0.0.1:${server.address().port}`;assert.ok(base)});
test('02 health',async()=>assert.equal((await request('/api/health')).data.database,'connected'));
test('03 database tables',async()=>{await db.getDb();assert.ok(db.all("SELECT name FROM sqlite_master WHERE type='table'").length>=16)});
test('04 seed categories',async()=>assert.equal((await request('/api/categories')).data.categories.length,3));
test('05 seed products',async()=>assert.equal((await request('/api/products')).data.products.length,5));
test('06 owner seed',async()=>assert.equal(db.one("SELECT role FROM admin_users WHERE phone='09120000000'").role,'owner'));
test('07 store seed',async()=>assert.equal((await request('/api/store')).data.store.store_name,'مرغ فروشی بهار'));
test('08 otp requires phone',async()=>assert.equal((await request('/api/auth/otp/request',{method:'POST',body:{}})).status,400));
test('09 otp validates phone',async()=>assert.equal((await request('/api/auth/otp/request',{method:'POST',body:{phone:'12'}})).status,400));
test('10 OTP request',async()=>assert.equal((await request('/api/auth/otp/request',{method:'POST',body:{phone:'09121111111'}})).data.otp,'123456'));
test('11 OTP rejects bad code',async()=>assert.equal((await request('/api/auth/otp/verify',{method:'POST',body:{phone:'09121111111',code:'1'}})).status,401));
test('12 OTP verify session',async()=>{let x=await request('/api/auth/otp/verify',{method:'POST',body:{phone:'09121111111',code:'123456'}});customer=x.data.token;assert.ok(customer)});
test('13 session auth',async()=>assert.equal((await request('/api/addresses',{token:customer})).status,200));
test('14 admin rejects stranger',async()=>assert.equal((await request('/api/admin/login',{method:'POST',body:{phone:'09129999999'}})).status,403));
test('15 admin login',async()=>{let x=await request('/api/admin/login',{method:'POST',body:{phone:'09120000000'}});owner=x.data.token;assert.equal(x.data.admin.role,'owner')});
test('16 product listing',async()=>{product=(await request('/api/products')).data.products[0];assert.ok(product.stock>0)});
test('17 product detail',async()=>assert.equal((await request('/api/products/'+product.id)).data.product.id,product.id));
test('18 add category admin',async()=>assert.equal((await request('/api/admin/categories',{method:'POST',token:owner,body:{name:'تستی'}})).status,201));
test('19 add product admin',async()=>assert.equal((await request('/api/admin/products',{method:'POST',token:owner,body:{name:'محصول تست',price:100000,unit:'piece',stock:3}})).status,201));
test('20 update inventory',async()=>{let x=await request('/api/admin/products/'+product.id,{method:'PATCH',token:owner,body:{stock:9}});assert.equal(x.data.product.stock,9)});
test('21 inactive hidden',async()=>{await request('/api/admin/products/'+product.id,{method:'PATCH',token:owner,body:{active:0}});assert.equal((await request('/api/products')).data.products.some(p=>p.id===product.id),false);await request('/api/admin/products/'+product.id,{method:'PATCH',token:owner,body:{active:1}})});
test('22 address auth required',async()=>assert.equal((await request('/api/addresses')).status,401));
test('23 create address',async()=>{let x=await request('/api/addresses',{method:'POST',token:customer,body:{province:'تهران',city:'تهران',address:'خیابان تست',latitude:35.7,longitude:51.4}});address=x.data.address.id;assert.ok(address)});
test('24 list addresses',async()=>assert.ok((await request('/api/addresses',{token:customer})).data.addresses.length));
test('25 quote rejects empty',async()=>assert.equal((await request('/api/cart/quote',{method:'POST',body:{items:[]}})).status,400));
test('26 quote minimum order',async()=>assert.equal((await request('/api/cart/quote',{method:'POST',body:{items:[{product_id:product.id,quantity:.1}]}})).status,400));
test('27 quote delivery fee',async()=>{let x=await request('/api/cart/quote',{method:'POST',body:{items:[{product_id:product.id,quantity:1}]}});assert.equal(x.data.delivery,30000)});
test('28 free delivery threshold',async()=>{let x=await request('/api/cart/quote',{method:'POST',body:{items:[{product_id:product.id,quantity:6}]}});assert.equal(x.data.delivery,0)});
test('29 create discount',async()=>assert.equal((await request('/api/admin/discounts',{method:'POST',token:owner,body:{code:'TEN',type:'percent',value:10}})).status,201));
test('30 percent discount',async()=>{let x=await request('/api/cart/quote',{method:'POST',body:{items:[{product_id:product.id,quantity:1}],discount_code:'TEN'}});assert.equal(x.data.discount,Math.floor(product.price*.1))});
test('31 discount invalid',async()=>assert.equal((await request('/api/cart/quote',{method:'POST',body:{items:[{product_id:product.id,quantity:1}],discount_code:'NO'}})).status,400));
test('32 order create',async()=>{let x=await request('/api/orders',{method:'POST',token:customer,body:{items:[{product_id:product.id,quantity:1}],address_id:address,payment_method:'mock_online',discount_code:'TEN'}});order=x.data.order;assert.equal(x.status,201)});
test('33 payment mock paid',async()=>assert.equal(db.one('SELECT status FROM payments WHERE order_id=?',[order.id]).status,'paid'));
test('34 discount usage',async()=>assert.equal(db.one("SELECT usage_count FROM discount_codes WHERE code='TEN'").usage_count,1));
test('35 order history',async()=>assert.ok((await request('/api/orders',{token:customer})).data.orders.length));
test('36 order tracking',async()=>assert.equal((await request('/api/orders/'+order.id,{token:customer})).data.order.status,'new'));
test('37 status transition',async()=>assert.equal((await request('/api/admin/orders/'+order.id+'/status',{method:'PATCH',token:owner,body:{status:'confirmed'}})).data.order.status,'confirmed'));
test('38 invalid transition',async()=>assert.equal((await request('/api/admin/orders/'+order.id+'/status',{method:'PATCH',token:owner,body:{status:'delivered'}})).status,400));
test('39 cancellation',async()=>assert.equal((await request('/api/admin/orders/'+order.id+'/status',{method:'PATCH',token:owner,body:{status:'cancelled'}})).data.order.status,'cancelled'));
test('40 owner adds admin',async()=>assert.equal((await request('/api/admin/admins',{method:'POST',token:owner,body:{phone:'09123333333',name:'مدیر'}})).status,201));
test('41 admin permission',async()=>{let t=(await request('/api/admin/login',{method:'POST',body:{phone:'09123333333'}})).data.token;assert.equal((await request('/api/admin/admins',{method:'POST',token:t,body:{phone:'09124444444',name:'x'}})).status,403)});
test('42 store close',async()=>{await request('/api/admin/store',{method:'PATCH',token:owner,body:{is_open:0}});assert.equal((await request('/api/cart/quote',{method:'POST',body:{items:[{product_id:product.id,quantity:1}]}})).status,400);await request('/api/admin/store',{method:'PATCH',token:owner,body:{is_open:1}})});
test('43 business hours',async()=>{await request('/api/admin/business-hours/1',{method:'PUT',token:owner,body:{open_time:'10:00',close_time:'20:00'}});assert.equal((await request('/api/store')).data.business_hours[1].open_time,'10:00')});
test('44 dashboard',async()=>assert.ok((await request('/api/admin/dashboard',{token:owner})).data.today_orders.count>=1));
test('45 reports',async()=>assert.ok('sales' in (await request('/api/admin/reports',{token:owner})).data.report));
test('46 admin logs',async()=>assert.ok((await request('/api/admin/logs',{token:owner})).data.logs.length));
test('47 persistence export',async()=>{db.save();assert.ok(require('fs').statSync(process.env.DB_FILE).size>100)});
test('48 persistence restart load',async()=>{db.resetForTests();await db.getDb();assert.ok(db.one('SELECT * FROM orders WHERE id=?',[order.id]))});
test('49 logout',async()=>assert.equal((await request('/api/auth/logout',{method:'POST',token:customer})).data.success,true));
test('50 shutdown',async()=>{await new Promise(r=>server.close(r));assert.ok(true)});
